/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Header file for the Ultrasonic driver
 *
 * Author : Ahmed Gamal
 *
 *******************************************************************************/
# include "ultrasonic.h"
# include "gpio.h"
# include "icu.h"
# include <util/delay.h> /* for delay*/

/* globale variable to detect the pulse */
volatile uint16 g_edgeCount = 0 ;
/* globale variable to detect the pulse time */
volatile uint16 g_timePulse = 0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	/*Initialize the ICU driver*/
	ICU_ConfigType configration = {F_CPU_8,RAISING};
	ICU_init(&configration);
	/*Setup the ICU call back function*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/* Setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}

/*
 * Description
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/* Send the pulse*/
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);
	_delay_us(20); /* wait 10us*/
	/* close the Trigger pin*/
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}

/*
 * Description
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	/* variable to save the distance */
	uint16 distance = 0 ;

	/*Send the trigger pulse */
	Ultrasonic_Trigger();
	/* wait for the falling edge */
	while(g_edgeCount != 2 );
	/* Calculate the distance*/
	distance =( 1+( g_timePulse / 58));
	/* clear the g_edge counter to remeasure the time */
	g_edgeCount =0 ;

	return distance ;
}

/*
 * Description
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount ++ ;
	if(g_edgeCount == 1 )
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect Falling edge*/
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Save the high time( Pulse time) */
		g_timePulse = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
	}
}
